### ISSUE TITLE
missing definition of basic types

### ISSUE THREAD

**Issue by maciejskorski** [supranational/sppark#19] opened 2023-09-28 17:27 UTC
For instance, the type `vec384` misses a definition

https://github.com/supranational/sppark/blob/fffd7349b29bb086d2a8147b227baf8b9ed006dd/ff/bls12-381.hpp#L82

**Comment by dot-asm** [comment] 2023-10-09 17:20
This is obviously duplicate of #18.

**Closed by dot-asm** 2023-10-09 17:20 UTC
